### ISSUE TITLE
could you put your commits in PR ?

### ISSUE THREAD

**Issue by ccoVeille** [meyermarcel/annot#6]
Hey @meyermarcel 

I can see now that you continued contributing to your tool. It thought it was stale because I received no notification for a while.
I got one when you created the last issue. So I came to see, and I keep working on it
https://github.com/meyermarcel/annot/commits/main/

But you didn't use PR https://github.com/meyermarcel/annot/pulls?q=is%3Apr

I would like to suggest you to commit in branches and then open PR.
In the very same way you would do if you were working in a team (assuming you are only one guy working on this)

But the community could help, maybe I'm the only watcher for now, I'm never sure when it's say 2 watchers.

This way we could look at your code, suggest you things, maybe spot a few errors, but also following your work

Thanks,

Respectfully,

Christophe

**Comment by meyermarcel** [comment]
See https://github.com/meyermarcel/annot/issues/5#issuecomment-2191993881

**Comment by ccoVeille** [comment]
Thanks
